networks:
  denodo-lab-net:
    external: true
services:
  backend:
    build: ./backend
    container_name: vqlforge-backend
    ports: 
      - "8000:8000" 
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    user: appuser
    networks:        
      - denodo-lab-net 
  frontend:
    build: ./frontend
    container_name: vqlforge-frontend
    ports:
      - "80:80"
    networks:
      - denodo-lab-net
    depends_on:
      - backend
