networks:
  app_network:
    external: true
    name: ${APP_NETWORK_NAME:-denodo-lab-net}

services:
  frontend:
    ports:
      - "${HOST_FRONTEND_PORT:-4999}:4999"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    ports:
      - "${HOST_BACKEND_PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      # Denodo credentials
      - DENODO_HOST=${DENODO_HOST}
      - DENODO_DB=${DENODO_DB}
      - DENODO_USER=${DENODO_USER}
      - DENODO_PW=${DENODO_PW}
      # AI KEY
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_MODEL_NAME=${AI_MODEL_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      # BACKEND
      - CONTAINER_BACKEND_PORT=${CONTAINER_BACKEND_PORT:-5000}
      # Files
      - APP_VDB_CONF=/opt/vdb_conf.yaml
    user: appuser
    volumes:
      - ${HOST_PROJECT_PATH}/backend/vdb_conf.yaml:/opt/vdb_conf.yaml


    networks:
      - app_network