networks:
  app_network:
    external: true
    name: ${APP_NETWORK_NAME:-denodo-lab-net}

services:
  frontend:
    ports:
      - "${HOST_FRONTEND_PORT:-4999}:4999"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    ports:
      - "${HOST_BACKEND_PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      # Denodo credentials
      - DENODO_HOST=${DENODO_HOST}
      - DENODO_DB=${DENODO_DB}
      - DENODO_USER=${DENODO_USER}
      - DENODO_PW=${DENODO_PW}
      # AI KEY
      - GEMINI_API_KEY=${AI_API_KEY}
      - CONTAINER_BACKEND_PORT=5000
    user: appuser
    networks:
      - app_network