[project]
name = "denodo-translate-assist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "denodo-sqlalchemy[flightsql]>=2.0.4",
    "fastapi>=0.115.12",
    "sqlalchemy>=2.0.40",
    "uvicorn[standard]>=0.34.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
# Since your code isn't in a directory matching the project name (denodo_translate_assist),
# explicitly tell hatch which files/directories ARE part of the package.
# In this case, it's just main.py.
include = [
    "main.py",
]